 
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-pipeline
 
serialPipeline:
  stages:
  - targetId: dev
    profiles: ["dev"]
 
  - targetId: prod
    profiles: ["prod"]
    requireApproval: true
 
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
gke:
  cluster: projects/project-b9b64406-bb96-4830-8f1/locations/us-central1-a/clusters/demo-cluster
 
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
gke:
  cluster: projects/project-b9b64406-bb96-4830-8f1/locations/us-central1-a/clusters/demo-cluster
