steps:
# Build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1 -a-docker.pkg.dev/project-b9b64406-bb96-4830-8f1/demo-ci-cd-repo/app', '.']
 
# Push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1 -a-docker.pkg.dev/project-b9b64406-bb96-4830-8f1/demo-ci-cd-repo/app']
 
# Trigger Cloud Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - deploy
  - releases
  - create
  - release-$BUILD_ID
  - --delivery-pipeline=demo-pipeline
  - --region=us-central1-a
  - --images=app=asia-south1-a-docker.pkg.dev/project-b9b64406-bb96-4830-8f1/demo-ci-cd-repo/app
options:
  logging: CLOUD_LOGGING_ONLY
