steps:
# Build image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'us-central1-docker.pkg.dev/project-b9b64406-bb96-4830-8f1/demo-repo/app',
    '.'
  ]

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/project-b9b64406-bb96-4830-8f1/demo-repo/app'
  ]

# Trigger Cloud Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - deploy
  - releases
  - create
  - release-$BUILD_ID
  - --delivery-pipeline=demo-pipeline
  - --region=us-central1
  - --images=app=us-central1-docker.pkg.dev/project-b9b64406-bb96-4830-8f1/demo-repo/app

options:
  logging: CLOUD_LOGGING_ONLY
