apiVersion: skaffold/v4beta1
kind: Config

metadata:
  name: demo-app

build:
  artifacts:
  - image: app
    context: .
    docker:
      dockerfile: Dockerfile

manifests:
  rawYaml:
  - deployment.yaml
  - service.yaml

deploy:
  kubectl: {}

profiles:
- name: dev
  patches:
  - op: add
    path: /spec/template/spec/nodeSelector
    value:
      env: dev

- name: prod
  patches:
  - op: add
    path: /spec/template/spec/nodeSelector
    value:
      env: prod