apiVersion: skaffold/v4beta1
kind: Config

metadata:
  name: demo-app

build:
  artifacts:
  - image: app
    context: .
    docker:
      dockerfile: Dockerfile

manifests:
  rawYaml:
  - k8s/deployment.yaml
  - k8s/service.yaml

deploy:
  kubectl: {}

profiles:
- name: dev
  deploy:
    kubectl:
      defaultNamespace: dev

- name: prod
  deploy:
    kubectl:
      defaultNamespace: prodk8s/